apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal-deployment
  labels:
    app: admin-portal
spec:
  replicas: 3  # Number of pod instances
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      containers:
      - name: admin-portal
        image: sowmyasantoshi4/admin-portal:latest  # The image to deploy
        ports:
        - containerPort: 9005
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
