version: '3'
services:
  shell:
    image: sowmyasantoshi4/shell:latest
    ports:
      - "9000:80"
    depends_on:
      - login
      - tracking
      - reports
      - admin
      - packages
    networks:
      - mfe-network

  login:
    image: sowmyasantoshi4/login:latest
    ports:
      - "9002:80"
    networks:
      - mfe-network

  tracking:
    image: sowmyasantoshi4/tracking:latest
    ports:
      - "9003:80"
    networks:
      - mfe-network

  reports:
    image: sowmyasantoshi4/reports:latest
    ports:
      - "9004:80"
    networks:
      - mfe-network

  admin:
    image: sowmyasantoshi4/admin-portal:latest
    ports:
      - "9005:80"
    networks:
      - mfe-network

  packages:
    image: sowmyasantoshi4/packages:latest
    ports:
      - "9006:80"
    networks:
      - mfe-network

networks:
  mfe-network:
    driver: bridge
