version: "3.0"
services:
  shell:
    build:
      context: ./shell
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - login
      - tracking
      - reports
      - admin
      - packages
    networks:
      - mfe-network

  login:
    build:
      context: ./login
      dockerfile: Dockerfile
    ports:
      - "9002:80"
    networks:
      - mfe-network

  tracking:
    build:
      context: ./tracking
      dockerfile: Dockerfile
    ports:
      - "9003:80"
    networks:
      - mfe-network

  reports:
    build:
      context: ./reports
      dockerfile: Dockerfile
    ports:
      - "9004:80"
    networks:
      - mfe-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "9005:80"
    networks:
      - mfe-network

  packages:
    build:
      context: ./packages
      dockerfile: Dockerfile
    ports:
      - "9006:80"
    networks:
      - mfe-network

networks:
  mfe-network:
    driver: bridge
