version: '3.8'

services:
  shell:
    build:
      context: ./shell
    expose:
      - "80"  # Expose port 80

  login:
    build:
      context: ./login
    expose:
      - "80"  # Expose port 80

  tracking:
    build:
      context: ./tracking
    expose:
      - "80"  # Expose port 80

  reports:
    build:
      context: ./reports
    expose:
      - "80"  # Expose port 80

  admin_portal:
    build:
      context: ./admin-portal
    expose:
      - "80"  # Expose port 80

  packages:
    build:
      context: ./packages
    expose:
      - "80"  # Expose port 80

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Bind Nginx to port 9000 on the host
    depends_on:
      - shell
      - login
      - tracking
      - reports
      - admin_portal
      - packages
