apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login-container
          image: sowmyasantoshi4/login-mfe:latest
          ports:
            - containerPort: 8080
          env:
            - name: SHELL_MFE_URL
              value: "http://shell-service/remoteEntry.js"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: login-loadbalancer
spec:
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
