apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: sowmyasantoshi4/login:latest
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  labels: 
    app: login
spec:
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9002
  type: ClusterIP