apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: sowmyasantoshi4/login-mfe:latest
          ports:
            - containerPort: 80
          env:
            - name: SHELL_MFE_URL
              value: "http://shell-service/remoteEntry.js"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
