apiVersion: apps/v1
kind: Deployment
metadata:
  name: packages
spec:
  replicas: 2
  selector:
    matchLabels:
      app: packages
  template:
    metadata:
      labels:
        app: packages
    spec:
      containers:
      - name: packages
        image: sowmyasantoshi4/packages:latest 
        ports:
        - containerPort: 9006
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: packages-service
  labels: 
    app: packages
spec:
  selector:
    app: packages
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9006
  type: ClusterIP