# reports-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports
  namespace: mfe-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
        - name: reports
          image: sowmyasantoshi4/reports:latest
          ports:
            - containerPort: 80
---
# reports-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: reports-service
  namespace: mfe-namespace
spec:
  type: NodePort
  selector:
    app: reports
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30084
