apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  # namespace: mfe-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
        - name: shell
          image: sowmyasantoshi4/shell:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: shell-service
  labels: 
    app: shell
spec:
  selector:
    app: shell
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: NodePort