apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
        - name: tracking
          image: sowmyasantoshi4/tracking:latest
          ports:
            - containerPort: 9003
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  labels: 
    app: tracking
spec:
  selector:
    app: tracking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9003
  type: ClusterIP