apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-deployment
  labels:
    app: tracking
spec:
  replicas: 3  # Number of pod instances
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
      - name: tracking
        image: sowmyasantoshi4/tracking:latest  # The image to deploy
        ports:
        - containerPort: 9003
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
