apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-deployment
  labels:
    app: reports
spec:
  replicas: 2  # Number of pod instances
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
      - name: reports
        image: sowmyasantoshi4/reports:latest  # The image to deploy
        ports:
        - containerPort: 9004
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
