apiVersion: apps/v1
kind: Deployment
metadata:
  name: packages-deployment
  labels:
    app: packages
spec:
  replicas: 3  # Number of pod instances
  selector:
    matchLabels:
      app: packages
  template:
    metadata:
      labels:
        app: packages
    spec:
      containers:
      - name: packages
        image: sowmyasantoshi4/packages:latest  # The image to deploy
        ports:
        - containerPort: 9006
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
