name: Build and Deploy adminMFE

on:
  push:
    paths:
      - 'admin-portal/**'  # Trigger this workflow only when changes happen in 'admin-portal' folder
    branches:
      - master  # Trigger only on pushes to 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/admin-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for adminMFE
      run: docker build -t sowmyasantoshi4/admin-mfe:latest ./adminMFE

    - name: Push Docker image to Docker Hub
      run: docker push sowmyasantoshi4/admin-mfe:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./adminMFE/deployment.yml
        kubectl apply -f ./adminMFE/service.yml
