name: Build and Deploy reportsMFE

on:
  push:
    paths:
      - 'reports/**'  # Trigger this workflow only when changes happen in 'reports' folder
    branches:
      - master  # Trigger only on pushes to 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for reportsMFE
      run: docker build -t sowmyasantoshi4/reports:latest ./reports

    - name: Push Docker image to Docker Hub
      run: docker push sowmyasantoshi4/reports:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Set up Kubectl
  #     uses: azure/setup-kubectl@v1
  #     with:
  #       version: 'latest'

  #   - name: Check if reports directory exists
  #     run: |
  #       echo "Checking if reports directory exists"
  #       ls
  #       echo "Attempting to list reports folder contents"
  #       ls -R ./reports

  #   - name: Deploy reportsMFE to Kubernetes
  #     run: |
  #       kubectl apply -f deployment.yml
  #       kubectl apply -f service.yml

  #   # Optional: Check deployment success
  #   - name: Check if Deployment was successful
  #     run: |
  #       kubectl get pods
  #       kubectl describe deployment reportsMFE
