name: Build and Deploy packagesMFE

on:
  push:
    paths:
      - 'packages/**'  # Trigger this workflow only when changes happen in 'packages' folder
    branches:
      - master  # Trigger only on pushes to 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/packages-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for packagesMFE
      run: docker build -t sowmyasantoshi4/packages-mfe:latest ./packagesMFE

    - name: Push Docker image to Docker Hub
      run: docker push sowmyasantoshi4/packages-mfe:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./packagesMFE/deployment.yml
        kubectl apply -f ./packagesMFE/service.yml
