name: Build and Deploy shellMFE

on:
  push:
    #paths:
     # - 'shell/**'  # Trigger this workflow only when changes happen in 'shell' folder
    branches:
      - master  # Trigger only on pushes to 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for shellMFE
      run: docker build -t sowmyasantoshi4/shell:latest ./shell

    - name: Push Docker image to Docker Hub
      run: docker push sowmyasantoshi4/shell:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./shell/deployment.yml
        kubectl apply -f ./shell/service.yml
