name: Build and Deploy trackingMFE

on:
  push:
    paths:
      - 'tracking/**'  # Trigger this workflow only when changes happen in 'tracking' folder
    branches:
      - master  # Trigger only on pushes to 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for trackingMFE
      run: docker build -t sowmyasantoshi4/tracking:latest ./tracking

    - name: Push Docker image to Docker Hub
      run: docker push sowmyasantoshi4/tracking:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Set up Kubectl
  #     uses: azure/setup-kubectl@v1
  #     with:
  #       version: 'latest'

  #   - name: Deploy trackingMFE to Kubernetes
  #     run: |
  #       kubectl apply -f ./deployment.yml
  #       kubectl apply -f ./service.yml
